miesiace=(msc for msc in ["styczeń","luty","marzec","kwiecień","maj","czerwiec",
"lipec","sierpień","wrzesień","październik","listopad","grudzień"])
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))